/**
 * Các mã quyền thao tác dùng để điều khiển UI theo capability.
 * Owner/Admin có thể bypass lớp permission chi tiết ở FE,
 * còn staff sẽ dựa vào các mã này để mở route và thao tác tương ứng.
 */
export const PERMISSIONS = {
  STAFF_DASHBOARD_VIEW: 'STAFF_DASHBOARD_VIEW',
  TABLE_VIEW: 'TABLE_VIEW',
  TABLE_ASSIGN: 'TABLE_ASSIGN',
  ORDER_VIEW: 'ORDER_VIEW',
  ORDER_CREATE: 'ORDER_CREATE',
  ORDER_UPDATE: 'ORDER_UPDATE',
  PAYMENT_PROCESS: 'PAYMENT_PROCESS',
  KDS_VIEW: 'KDS_VIEW',
  KDS_UPDATE: 'KDS_UPDATE',
  INVENTORY_VIEW: 'INVENTORY_VIEW',
  INVENTORY_IMPORT: 'INVENTORY_IMPORT',
  INVENTORY_ADJUST: 'INVENTORY_ADJUST',
  INVENTORY_WASTE: 'INVENTORY_WASTE',
  SCHEDULE_VIEW: 'SCHEDULE_VIEW',
  SHIFT_VIEW: 'SHIFT_VIEW',
} as const;

export type PermissionCode = typeof PERMISSIONS[keyof typeof PERMISSIONS];

/**
 * Gom nhóm quyền tối thiểu để mở từng route staff.
 * Dùng `some()` thay vì `every()` để hỗ trợ các token cũ
 * chưa phát đầy đủ mã quyền tổng quát như `INVENTORY_VIEW`.
 */
export const STAFF_ROUTE_PERMISSIONS = {
  DASHBOARD: [PERMISSIONS.STAFF_DASHBOARD_VIEW],
  TABLES: [PERMISSIONS.TABLE_VIEW, PERMISSIONS.TABLE_ASSIGN, PERMISSIONS.ORDER_CREATE],
  ORDERS: [
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.PAYMENT_PROCESS,
  ],
  PAYMENT: [PERMISSIONS.PAYMENT_PROCESS],
  KDS: [PERMISSIONS.KDS_VIEW, PERMISSIONS.KDS_UPDATE],
  INVENTORY: [
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_IMPORT,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.INVENTORY_WASTE,
  ],
  MY_SHIFTS: [PERMISSIONS.SCHEDULE_VIEW, PERMISSIONS.SHIFT_VIEW],
  POS_ORDER: [PERMISSIONS.ORDER_CREATE, PERMISSIONS.ORDER_VIEW],
  POS_PAYMENT: [PERMISSIONS.PAYMENT_PROCESS],
  POS_MANAGEMENT: [
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.PAYMENT_PROCESS,
  ],
} as const;
