/**
 * Các mã quyền thao tác dùng để điều khiển UI theo capability.
 * Owner/Admin có thể bypass lớp permission chi tiết ở FE,
 * còn staff sẽ dựa vào các mã này để mở route và thao tác tương ứng.
 */
export const PERMISSIONS = {
  STAFF_DASHBOARD_VIEW: 'STAFF_DASHBOARD_VIEW',
  TABLE_VIEW: 'TABLE_VIEW',
  TABLE_ASSIGN: 'TABLE_ASSIGN',
  ORDER_VIEW: 'ORDER_VIEW',
  ORDER_CREATE: 'ORDER_CREATE',
  ORDER_UPDATE: 'ORDER_UPDATE',
  ORDER_CANCEL: 'ORDER_CANCEL',
  MENU_VIEW: 'MENU_VIEW',
  MENU_EDIT: 'MENU_EDIT',
  // Backend hiện đang phát PAYMENT_CREATE trong JWT; giữ thêm PAYMENT_PROCESS để tương thích token cũ.
  PAYMENT_CREATE: 'PAYMENT_CREATE',
  PAYMENT_PROCESS: 'PAYMENT_PROCESS',
  KDS_VIEW: 'KDS_VIEW',
  KDS_UPDATE: 'KDS_UPDATE',
  INVENTORY_VIEW: 'INVENTORY_VIEW',
  INVENTORY_IMPORT: 'INVENTORY_IMPORT',
  INVENTORY_ADJUST: 'INVENTORY_ADJUST',
  INVENTORY_WASTE: 'INVENTORY_WASTE',
  SCHEDULE_VIEW: 'SCHEDULE_VIEW',
  SHIFT_VIEW: 'SHIFT_VIEW',
} as const;

export type PermissionCode = typeof PERMISSIONS[keyof typeof PERMISSIONS];

// Quyền mở luồng thanh toán cần hỗ trợ cả mã mới từ backend và mã FE cũ để tránh redirect sai route.
const PAYMENT_ROUTE_PERMISSIONS = [PERMISSIONS.PAYMENT_CREATE, PERMISSIONS.PAYMENT_PROCESS] as const;

/**
 * Gom nhóm quyền tối thiểu để mở từng route staff.
 * Dùng `some()` thay vì `every()` để hỗ trợ các token cũ
 * chưa phát đầy đủ mã quyền tổng quát như `INVENTORY_VIEW`.
 */
export const STAFF_ROUTE_PERMISSIONS = {
  DASHBOARD: [PERMISSIONS.STAFF_DASHBOARD_VIEW],
  TABLES: [PERMISSIONS.TABLE_VIEW, PERMISSIONS.TABLE_ASSIGN, PERMISSIONS.ORDER_CREATE],
  ORDERS: [
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_UPDATE,
    ...PAYMENT_ROUTE_PERMISSIONS,
  ],
  PAYMENT: [...PAYMENT_ROUTE_PERMISSIONS],
  KDS: [PERMISSIONS.KDS_VIEW, PERMISSIONS.KDS_UPDATE],
  MENU: [PERMISSIONS.MENU_VIEW],
  RECIPES: [PERMISSIONS.MENU_VIEW],
  INVENTORY: [
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_IMPORT,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.INVENTORY_WASTE,
  ],
  MY_SHIFTS: [PERMISSIONS.SCHEDULE_VIEW, PERMISSIONS.SHIFT_VIEW],
  // Route tạo/chỉnh đơn chỉ dành cho user có quyền tạo đơn.
  POS_ORDER: [PERMISSIONS.ORDER_CREATE],
  POS_PAYMENT: [...PAYMENT_ROUTE_PERMISSIONS],
  POS_MANAGEMENT: [PERMISSIONS.ORDER_VIEW],
} as const;
